version: "3.7"

services:
    tika:
        build:
            context: ./
            dockerfile: ./docker/tika/Dockerfile
        volumes: 
            - .:/usr/src/app
        env_file:
            - docker.tika.environment
        networks: 
            - default
        ports:
            - 9998:9998
    python:
        build:
            context: ./
            dockerfile: ./docker/python/Dockerfile
        volumes: 
            - .:/usr/src/app
        env_file:
            - docker.python.environment
        networks: 
            - default
        ports:
            - 8080:8080